### ISSUE TITLE
get_username returns null

### ISSUE THREAD

**Issue by SusgUY446** [h4rldev/hshell#2]
![image](https://github.com/h4rldev/hshell/assets/129160115/a175dc07-f1c1-40be-957a-87583dbc3d39)
![image](https://github.com/h4rldev/hshell/assets/129160115/a86d2159-8983-403b-8684-38fc79e8fd56)

**Comment by h4rldev** [comment]
Ill check it out

**Comment by h4rldev** [comment]
Can't reproduce.

**Comment by SusgUY446** [comment]
bruh
